### ISSUE TITLE
Best way to automate round trip through shfmt

### ISSUE THREAD

**Issue by focusaurus** [mark-hahn/shell-it#2]
I've been trying various packages and macros this morning and I think rather than requesting a specific feature, I'll just file an issue describing my desired functionality and see whether you think this can be done with shell-it, shell-it combined with something like atom-macros, or have other suggestions.

My end goal is to have this flow:
- Given starting state of I have a shell script open in atom editor
- hit a keyboard shortcut (`ctrl-. f s s` in my case)
- have the following happen
  - select all
  - pipe selected text through `shfmt -i 2`
  - replace selection with stdout from that command

Running this manually with `shell-it` does work, it's just tedious. Something that might help would be a command history with shell-it so I could just hit up arrow, but ultimately I'd like to get the whole thing done with a single keyboard shortcut.

I'd love to hear your thoughts as to the best way to get this working. Thanks!

I guess maybe writing a plugin for atom-community/formatter might be a decent approach.

**Comment by mark-hahn** [comment]
One way would be to add these features with a pull request, it wouldn't be
too hard.  :-)

However, there is probably a macro package available that lets you record
and play-back commands.  If there isn't then there should be.

**Comment by focusaurus** [comment]
I've got this working as its own atom plugin now, so I'll close this issue.
