### ISSUE TITLE
Bind shell command to hotkey

### ISSUE THREAD

**Issue by W4RH4WK** [mark-hahn/shell-it#5]
Is there a way to bind a certain shell command to a hotkey using this package. Say, make it so F5 will filter my selection with the `sort` command.

**Comment by mark-hahn** [comment]
No, there is no way to do that now.  I would guess that if you asked how to run a script from a hot-key on the forum someone could tell you a way to do it.

**Comment by W4RH4WK** [comment]
Okay, thank you.
